project:
  type: website
  output-dir: ./_site

babelquarto:
  languagecodes:
  - name: en
    text: "English"
  - name: fr
    text: "Français"
  mainlanguage: 'fr'
  languages: ['en']
  languagelinks: sidebar
title-en: "STT-2200: Data Analysis"
description-en: "Website for STT-2200"
author-en: "Steven Golovkine"
lang: fr


website:
  title: "STT-2200: Analyse de données"
  page-navigation: true
  site-url: https://stt2200.netlify.app
  repo-url: https://github.com/StevenGolovkine/UL-STT2200
  repo-actions: [issue, source]
  open-graph: true

  page-footer:
    center: "2025 | <strong>Steven Golovkine</strong> | <a class='link-footer' href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>CC BY-NC-SA 4.0</a>"

  sidebar: 
    logo: "./include/logo.png"
    pinned: true
    align: center
    toc-location: right
    search: true
    collapse-level: 1
    tools: 
      - icon: github
        href: https://github.com/StevenGolovkine/UL-STT2200
        text: "Github organization"
    contents:
      - section: "Informations"
        contents: 
          - href: informations/general.qmd
            text: Générales
          - href: informations/description.qmd
            text: Description
          - href: informations/schedule.qmd
            text: Plan
          - section: "Évaluations"
            href: informations/evaluations.qmd 
            contents: 
              - informations/mcq.qmd
          - href: informations/materials.qmd 
            text: Matériel
      - section: "Modules"
        contents: 
          - href: contents/01-introduction.qmd 
            text: 01 - Introduction 
          - href: contents/02-revisions.qmd 
            text: 02 - Révisions
            contents:
              - contents/remainders/01-linear-algebra.qmd
              - contents/remainders/02-probabilities.qmd 
              - contents/remainders/03-programming.qmd
          - href: contents/03-generalities.qmd 
            text: 03 - Généralités
            contents:
              - contents/generalities/01-stat.qmd
              - contents/generalities/02-spaces.qmd
              - contents/generalities/03-distance.qmd 
              - contents/generalities/04-bias-variance.qmd 
              - contents/generalities/05-model-evaluation.qmd
          - href: contents/04-dimension.qmd
            text: 04 - Dimension
            contents:
              - contents/dimension/01-pca.qmd 
              - contents/dimension/02-ca.qmd 
              - contents/dimension/03-mca.qmd 
          - href: contents/05-supervisee.qmd 
            text: 05 - Supervisée
            contents: 
              - contents/supervised/01-discriminant.qmd
              - contents/supervised/02-tree.qmd
              - contents/supervised/03-ensemble.qmd
          - href: contents/06-nonsupervisee.qmd 
            text: 06 - Non-supervisée
            contents:
              - contents/unsupervised/01-kmeans.qmd 
              - contents/unsupervised/02-hierarchy.qmd
              - contents/unsupervised/03-gaussian-mixtures.qmd
          - href: contents/07-further.qmd 
            text: 07 - Éthique 
          - href: contents/08-conclusion.qmd 
            text: 08 - Conclusion


bibliography: ./include/biblio.bib

format:
  html:
    theme:
      light: ./include/ulaval.scss
      dark: ./include/ulaval-dark.scss
    code-copy: true
    code-overflow: wrap 
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    include-after-body: include/webex.js


freeze: auto
editor: visual
