--- 
title: "Révisions"
subtitle: "Algèbre linéaire"
author: "Steven Golovkine"
lang: fr
date: "05 sept. 2025"
date-format: "DD MMM YYYY"
slide-number: c/t
title-logo: ../include/logo-ul.png
format:
  revealjs:
    theme: [default, ../include/ulaval-slide.scss]
    chalkboard:
      src: annotation/02-revisions-algebre-slides-annotation.json
    width: 1280
    height: 720
    template-partials:
      - title-slide.html
--- 

## Plan de la présentation

<br>

1. Propriétés matricielles

2. Valeurs et vecteurs propres

3. Diagonalisation de matrices


# Propriétés matricielles

## Notations de base

<br>

- $M_{n, m}(\mathbb{R})$ : matrices à $n$ lignes et $m$ colonnes

- $M_{n}(\mathbb{R})$ : matrices carrées de taille $n$  

- $I_n$ : matrice identité de taille $n$

- $u, v \in \mathbb{R}^n$ : vecteurs colonnes

## Propriétés du déterminant

<br>

::: {.callout-note icon=false}
## Propriétés

* $\det(A^\top) = \det(A)$

* $\det(AB) = \det(A)\det(B)$

* $\det(A^{-1}) = \frac{1}{\det(A)}$

:::

## Propriétés du déterminant

<br>

Cas particulier où $A \in M_{2}(\mathbb{R})$. 

Soit $A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$. Alors 

$$\det(A) = ad - bc.$$


## Propriété du déterminant : exemple (Wooclap: KFFPDJ)

<br>

$$A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, \quad B = \begin{pmatrix} 2 & 0 \\ 1 & 1 \end{pmatrix}$$

. . .

On trouve que $\det(A) = 4 - 6 = -2$, $\det(B) = 2 - 0 = 2$. Donc

$$\det(AB) = \det(A) \det(B) = -4$$


## Inverse de matrices 

<br>

::: {.callout-note icon=false}
## Propriété

Si $A$ et $B$ sont inversibles, alors :
$(AB)^{-1} = B^{-1} A^{-1}$.
:::


## Inverse de matrices

<br>

Cas particulier où $A \in M_{2}(\mathbb{R})$. 

Soit $A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$. Alors 

$$A^{-1} = \frac{1}{ad - bc}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}.$$


## Inverse de matrices : exemple (Wooclap: KFFPDJ)

<br>

$$A = \begin{pmatrix} 2 & 0 \\ 0 & 3 \end{pmatrix}, \quad B = \begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix}$$

. . .

On a :
$AB = \begin{pmatrix} 2 & 2 \\ 0 & 3 \end{pmatrix},$ donc $(AB)^{-1} = \begin{pmatrix} 1/2 & -1/3 \\ 0 & 1/3 \end{pmatrix}$.

Et effectivement : $B^{-1}A^{-1} = \begin{pmatrix} 1 & -1 \\ 0 & 1 \end{pmatrix} \begin{pmatrix} 1/2 & 0 \\ 0 & 1/3 \end{pmatrix} = \begin{pmatrix} 1/2 & -1/3 \\ 0 & 1/3 \end{pmatrix}$.


## Propriétés de la trace

<br>

La trace de la matrice $A \in M_{n}(\mathbb{R})$ est la somme des éléments diagonaux
$$\text{tr}(A) = \sum_{i=1}^{n} a_{ii}.$$

## Propriétés de la trace

<br>

::: {.callout-note icon=false}
## Propriétés

* $\text{tr}(A) = \text{tr}(A^{\top})$

* $\text{tr}(A + B) = \text{tr}(A) + \text{tr}(B)$

* $\text{tr}(MN^{\top}) = \text{tr}(N^{\top}M)$

:::


## Propriétés de la trace : exemple (Wooclap: KFFPDJ)

<br>

Soit $X \in M_{n, p}(\mathbb{R})$ avec $p < n$ et de rang $p$, et donc telle que $X^\top X$ est de dimension $p \times p$ et inversible. Quelle est la valeur de la trace de $X (X^\top X)^{-1} X^\top$ ?

. . .

\begin{align*}
 \text{tr}(X (X^\top X)^{-1} X^\top) &= \text{tr}(X^\top X (X^\top X)^{-1})\\
 &= \text{tr}(I_p) \\
 &= p.
\end{align*}


## Matrices spéciales


::: {.callout-important icon=false}
## Définitions

**Matrice définie positive :** $A$ est définie positive si 
$$\text{pour tout } u \neq 0,\quad u^\top A u > 0.$$

**Matrice orthogonale :** $A$ est orthogonale si 
$$A^\top A = A A^\top = I_n.$$
:::



## Comment montrer qu'une matrice est définie positive ?

<br>

Soit $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$ et pour tout $u = \begin{pmatrix} x \\ y \end{pmatrix} \neq 0$, on a :
\begin{align*}
u^\top A u &= \begin{pmatrix} x & y \end{pmatrix} \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix} \\
  &= 2x^2 + 2xy + 2y^2 \\
  &= x^2 + y^2 + (x+y)^2 > 0.
\end{align*}

Donc $A$ est définie positive.


# Valeurs et vecteurs propres

## Valeurs et vecteurs propres

::: {.notes}
Faire un dessin pour Au = lu.
:::

::: {.callout-important icon=false}
## Définitions

Soit $A \in M_{n}(\mathbb{R})$. Le scalaire $\lambda \in \mathbb{R}$ est une **valeur propre** de $A$ s'il existe $u \neq 0$ tel que :
$Au = \lambda u$.

$u$ est le **vecteur propre** correspondant à $\lambda$.

Le **spectre** de $A$, noté $\text{sp}(A)$, est l'ensemble des valeurs propres.
:::

## Valeurs et vecteurs propres : exemple

$$A = \begin{pmatrix} 3 & 1 \\ 0 & 2 \end{pmatrix}$$

. . .

**Calcul des valeurs propres :**
$$\det(A - \lambda I) = \det\begin{pmatrix} 3-\lambda & 1 \\ 0 & 2-\lambda \end{pmatrix} = (3-\lambda)(2-\lambda)$$

Donc $\lambda_1 = 3$ et $\lambda_2 = 2$.


## Valeurs et vecteurs propres : exemple

$$A = \begin{pmatrix} 3 & 1 \\ 0 & 2 \end{pmatrix}$$

. . .

**Calcul des vecteurs propres :**

- Pour $\lambda_1 = 3$ : $u_1 = \begin{pmatrix} 1 \\ 0 \end{pmatrix}$.

- Pour $\lambda_2 = 2$ : $u_2 = \begin{pmatrix} 1 \\ -1 \end{pmatrix}$.


## Propriétés des vecteurs propres

::: {.callout-note icon=false}
## Propriétés

* Si $u$ est vecteur propre pour $\lambda$, alors $cu$ l'est aussi (pour $c \neq 0$).

* **Pour matrices symétriques :** Si $u_1$ et $u_2$ sont deux vecteurs propres correspondent à des valeurs propres différentes, alors :
$$u_1^\top u_2 = 0 \text{ (orthogonalité)}.$$
:::

## Preuve de l'orthogonalité


Soient $\lambda_1 \neq \lambda_2$ et $Au_1 = \lambda_1 u_1$, $Au_2 = \lambda_2 u_2$.

. . .

On a 
$$\lambda_1 u_1^\top u_2 = u_1^\top A u_2 = \lambda_2 u_1^\top u_2.$$

. . .

Donc
$$(\lambda_1 - \lambda_2)u_1^\top u_2 = 0$$

. . .

Comme $\lambda_1 \neq \lambda_2$, on a nécessairement $u_1^\top u_2 = 0$


**→ Cette propriété est cruciale pour l'ACP !**


## Caractérisation des valeurs propres

<br>

::: {.callout-note icon=false}
## Propriétés

* **Matrice symétrique** → toutes les valeurs propres sont **réelles**.

* **Matrice définie positive** → toutes les valeurs propres sont **strictement positives**.

:::

## Caractérisation des valeurs propres : exemple

<br>

Soit $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix} \text{ (symétrique et définie positive)}$.

. . .

Valeurs propres : $\lambda_1 = 3, \lambda_2 = 1$ (toutes réelles et > 0).

Vecteurs propres : $u_1 = \begin{pmatrix} 1 \\ 1 \end{pmatrix}, u_2 = \begin{pmatrix} 1 \\ -1 \end{pmatrix}$.

Vérifions l'orthogonalité : $u_1^\top u_2 = 1 \times 1 + 1 \times (-1) = 0$.


# Diagonalisation

## Diagonalisation de matrices

<br>

::: {.callout-important icon=false}
## Définition

Une matrice $A$ est **diagonalisable** s'il existe $P$ inversible et $D$ diagonale telles que :
$$A = P D P^{-1} \Leftrightarrow P^{-1} A P = D.$$
:::

. . .

**Interprétation :** On peut "simplifier" $A$ en changeant de base.


## Théorème de décomposition spectrale

<br>

::: {.callout-important icon=false}
## Théorème 

Pour toute matrice **symétrique** $A$, il existe une matrice **orthogonale** $P$ telle que :
$A = P \Lambda P^\top$
où $\Lambda = \text{diag}(\lambda_1, \ldots, \lambda_n)$.

:::

La matrice $P$ est formée des vecteurs propres de $A$ et $\Lambda$ est la matrice diagonale des valeurs propres associées.

## Exemple

En reprenant l'example précédent.

Soit $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$. On a $P = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}$ et $\Lambda = \begin{pmatrix} 3 & 0 \\ 0 & 1 \end{pmatrix}.$

On peut vérifier le théorème de décomposition spectrale :

$$P \Lambda P^\top = \frac{1}{2}\begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}\begin{pmatrix} 3 & 0 \\ 0 & 1 \end{pmatrix}\begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix} = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix} = A.$$


## Lien avec le déterminant et la trace

<br>

::: {.callout-note icon=false}
## Propriétés

Si la matrice $A$ a pour valeurs propres $\lambda_1, \ldots, \lambda_n$ :

* $\det(A) = \prod_{i=1}^{n} \lambda_i$.

* $\text{tr}(A) = \sum_{i=1}^{n} \lambda_i$.

:::

## Lien avec le déterminant et la trace : exemple

<br>

Soit $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$. On a vu que ses valeurs propres sont $\lambda_1 = 3$ et $\lambda_2 = 1$.

On peut donc vérifier les formules pour le déterminant et la trace :

$$\det(A) = 4 - 1 = 3 = 3 \times 1 = \lambda_1 \lambda_2,$$

$$\text{tr}(A) = 2 + 2 = 4 = 3 + 1 = \lambda_1 + \lambda_2.$$
