{
  "hash": "5f8de5e56be9e0f3c1dfdfcb4b1ff90c",
  "result": {
    "engine": "knitr",
    "markdown": "--- \ntitle: \"Dimension\"\nsubtitle: \"Analyse des correspondances multiples\"\nauthor: \"Steven Golovkine\"\nlang: fr\ndate: \"10 oct. 2025\"\ndate-format: \"DD MMM YYYY\"\nslide-number: c/t\ntitle-logo: ../include/logo-ul.png\nformat:\n  revealjs:\n    theme: [default, ../include/ulaval-slide.scss]\n    chalkboard:\n      src: annotation/04-dimension-mca-slides-annotation.json\n    width: 1280\n    height: 720\n    template-partials:\n      - title-slide.html\n--- \n\n\n\n## Introduction à l'ACM\n\n<br>\n\nL'Analyse des Correspondances Multiples (ACM) est un prolongement de l'AFC pour analyser plus de deux variables qualitatives.\n\nPrincipe fondamental : Transformation préalable par codage disjonctif complet.\n\n## Plan\n\n<br>\n\n1. La théorie de l'analyse des correspondances multiples \n\n2. L'ACM en pratique\n\n3. Exemple : \n\n\n## Notation de base\n\n<br>\n\n- $n$ : nombre d'individus (observations)\n\n- $Q$ : nombre de variables (questions)  \n\n- $J_q$ : nombre de modalités de la variable $q$\n\n- $J$ : nombre total de modalités ($J = \\sum_{q=1}^Q J_q$)\n\nObjectif : Représenter graphiquement les relations entre toutes ces modalités.\n\n\n## Codage disjonctif complet\n\n::: {.callout-warning}\n## Définition\n\nTableau binaire $Z$ ($n \\times J$) contenant uniquement des 0 et des 1.\n:::\n\n. . .\n\n- Chaque variable → ses modalités\n\n- Individu possède modalité → code 1\n\n- Individu ne possède pas modalité → code 0\n\n- **Disjonctif** : au plus une modalité par variable\n\n- **Complet** : au moins une modalité par variable\n\n\n## Exemple concret - Données\n\n<br> \n\nProduits avec Type et Prix:\n\n| Produit | Type | Prix (\\$) |\n|---------|------|----------|\n| Nike | Hoodie | 256.72 |\n| Puma | Joggers | 221.26 |\n| Off-W | Hoodie | 198.45 |\n| Supreme | Hoodie | 235.50 |\n\nVariable Prix → 3 classes : <200\\$, [200\\$-250\\$], >250\\$\n\n## Exemple - Codage disjonctif complet\n\n<br> \n\nTableau transformé $Z$ :\n\n| Produit | Hoodie | Joggers | Sneakers | <200\\$ | [200\\$-250\\$] | >250\\$ |\n|---------|:------:|:-------:|:--------:|:-----:|:----------:|:-----:|\n| Nike | 1 | 0 | 0 | 0 | 0 | 1 |\n| Puma | 0 | 1 | 0 | 0 | 1 | 0 |\n| Off-W | 1 | 0 | 0 | 1 | 0 | 0 |\n| Supreme | 1 | 0 | 0 | 0 | 1 | 0 |\n\nChaque ligne somme à $Q = 2$ (2 variables).\n\n## Propriétés du tableau Z\n\n<br>\n\n::: {.callout-important}\n## Propriétés\n\n1. **Somme par ligne** : $\\sum_{j=1}^J z_{ij} = Q$ (constante)\n\n2. **Somme totale** : $\\sum_{i,j} z_{ij} = nQ$ \n\n3. **Somme par colonne** : $\\sum_{i=1}^n z_{ij} = n_j$ (effectif modalité $j$)\n\n:::\n\n\n## Perte d'information\n\n<br>\n\nVariables quantitatives → Classes : Perte d'information inévitable.\n\n- Valeur précise → Appartenance à une classe\n\n- Exemple : 256.72\\$ → >250\\$\n\n- Compromis : Granularité vs interprétabilité\n\n\nEnjeu : Choisir des classes pertinentes pour le problème étudié.\n\n## Tableau de Burt\n\n<br>\n\n::: {.callout-warning}\n## Définition\n\n$B = Z^\\top Z$ (matrice $J \\times J$)\n:::\n\n\n## Propriétés du tableau de Burt\n\n<br>\n\nTaille : $J \\times J$ (nombre total de modalités)\n\n. . .\n\nBlocs diagonaux : Matrices diagonales\n\n  → Éléments = effectifs de chaque modalité\n\n. . .\n\nBlocs non-diagonaux : Tableaux de contingence  \n\n  → Croisement entre variables $q$ et $q'$\n\n. . .\n\nSymétrie : $B = B^\\top$\n\n## Équivalence mathématique\n\n<br>\n\nL'ACM peut s'effectuer sur :\n\n- Le tableau disjonctif complet $Z$\n\n- Le tableau de Burt $B = Z^\\top Z$\n\nRésultat → Les deux approches donnent les mêmes facteurs!\n\nCette équivalence offre une flexibilité computationnelle.\n\n## Éléments propres de Z\n\nAnalyse directe - Vecteurs propres de :\n\n$$S = \\frac{1}{Q} Z^\\top Z D_J^{-1}$$\noù $D_J = \\text{diag}(n_1, \\ldots, n_J)$.\n\nCoordonnées profils-lignes :\n$$\\Phi_k = n Z D_J^{-1} u_k$$\n\n## Éléments propres de Z\n\nAnalyse duale - Vecteurs propres de :\n$$T = \\frac{1}{Q} Z D_J^{-1} Z^\\top$$\noù $D_J = \\text{diag}(n_1, \\ldots, n_J)$.\n\nCoordonnées profils-colonnes :\n$$\\Psi_k = n D_J^{-1} Z^\\top v_k$$\n\n## Éléments propres de B\n\nTableau de Burt symétrique → Analyse directe = duale\n\nVecteurs propres de :\n$$S' = \\frac{1}{Q^2} B^\\top D_J^{-1} B D_J^{-1}$$\n\n. . .\n\nOn peut réécrire $S'$ comme :\n$$S' = \\frac{1}{Q^2} Z^\\top Z D_J^{-1} Z^\\top Z D_J^{-1}$$\n\n## Relation entre valeurs propres\n\n<br>\n\nSi $\\lambda$ est valeur propre de $S$ (analyse de $Z$), alors $\\lambda^2$ est valeur propre de $S'$ (analyse de $B$).\n\nConséquence : \n\n- Mêmes vecteurs propres pour $Z$ et $B$.\n\n- Valeurs propres de $B$ = carrés des valeurs propres de $Z$.\n\n\n\n## Encodage des variables quantitatives\n\n\nChoix des bornes crucial pour la qualité de l'analyse.\n\n. . .\n\nApproches recommandées :\n\n- Analyser la distribution (histogrammes)\n\n- Bornes pertinentes au domaine d'étude\n\n- Éviter les classes peu informatives\n\n. . .\n\nApproche déconseillée :\n\n- Effectifs égaux automatiques\n\n- Classes sans sens métier\n\n## Encodage des variables qualitatives\n\nModalités \"naturelles\" mais problèmes potentiels.\n\n. . .\n\nEffectifs déséquilibrés :\n\n- Modalités très rares vs très fréquentes\n\n- Impact sur la représentation\n\n. . .\n\nSolutions potentielles :\n\n- Regroupements pertinents (connaissance du domaine)\n\n- Éviter la répartition aléatoire\n\n- Préserver le sens des modalités\n\n## Exemple : le succès des étudiants {.smaller .scrollable}\n\nOn considère le jeu de données suivant :\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Hours_Studied |Attendance |Parental_Involvement |Extracurricular_Activities |Sleep_Hours |School_Type |\n|:-------------|:----------|:--------------------|:--------------------------|:-----------|:-----------|\n|21-30         |71-90      |Low                  |No                         |<=7         |Public      |\n|11-20         |0-70       |Low                  |No                         |>7          |Public      |\n|21-30         |91-100     |Medium               |Yes                        |<=7         |Public      |\n|21-30         |71-90      |Low                  |Yes                        |>7          |Public      |\n|11-20         |91-100     |Medium               |Yes                        |<=7         |Public      |\n|11-20         |71-90      |Medium               |Yes                        |>7          |Public      |\n\n\n:::\n:::\n\n\n## Exemple : le succès des étudiants {.smaller}\n\n::: panel-tabset\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(FactoMineR)\nlibrary(factoextra)\nres_mca <- df |>\n  MCA(graph = FALSE)\nfviz_eig(res_mca)\nget_eigenvalue(res_mca)\n```\n:::\n\n\n### Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-dimension-mca-slides-annotated_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n### Valeurs propres\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|      | eigenvalue| variance.percent| cumulative.variance.percent|\n|:-----|----------:|----------------:|---------------------------:|\n|Dim.1 |  0.1984565|         11.90739|                    11.90739|\n|Dim.2 |  0.1898757|         11.39254|                    23.29993|\n|Dim.3 |  0.1814721|         10.88833|                    34.18826|\n|Dim.4 |  0.1773147|         10.63888|                    44.82714|\n|Dim.5 |  0.1672860|         10.03716|                    54.86430|\n\n\n:::\n:::\n\n\n:::\n\n\n## Exemple : le succès des étudiants {.smaller}\n\n::: panel-tabset\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfviz_mca_biplot(\n  res_mca, \n  repel = TRUE,\n  label = \"none\",\n  ggtheme = theme_minimal()\n)\n```\n:::\n\n\n### Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-dimension-mca-slides-annotated_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n\n\n## Exemple : le succès des étudiants {.smaller}\n\n::: panel-tabset\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfviz_mca_var(\n  res_mca,\n  choice = \"mca.cor\", \n  repel = TRUE,\n  ggtheme = theme_minimal()\n)\n```\n:::\n\n\n### Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-dimension-mca-slides-annotated_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n\n\n## Exemple : le succès des étudiants {.smaller}\n\n::: panel-tabset\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfviz_mca_var(\n  res_mca,\n  repel = TRUE,\n  ggtheme = theme_minimal()\n)\n```\n:::\n\n\n### Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-dimension-mca-slides-annotated_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n\n## Exemple : le succès des étudiants {.smaller}\n\n::: panel-tabset\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfviz_mca_var(\n  res_mca,\n  col.var = \"cos2\",\n  gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"), \n  repel = TRUE,\n  ggtheme = theme_minimal()\n)\n```\n:::\n\n\n### Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-dimension-mca-slides-annotated_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n\n## Exemple : le succès des étudiants {.smaller}\n\n::: panel-tabset\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfviz_mca_ind(\n  res_mca,\n  label = \"none\",\n  col.ind = \"cos2\", \n  gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"),\n  repel = TRUE,\n  ggtheme = theme_minimal()\n)\n```\n:::\n\n\n### Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-dimension-mca-slides-annotated_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n\n\n\n## Exemple : le succès des étudiants {.smaller}\n\n::: panel-tabset\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfviz_mca_ind(\n  res_mca, \n  label = \"none\",\n  habillage = \"Hours_Studied\",\n  palette = c(\"#D81B60\", \"#1E88E5\", \"#FFC107\", \"#004D40\"),\n  addEllipses = TRUE, ellipse.type = \"confidence\",\n  ggtheme = theme_minimal()\n) \n```\n:::\n\n\n### Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-dimension-mca-slides-annotated_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n### Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04-dimension-mca-slides-annotated_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n\n\n\n\n## Avantages de l'ACM\n\n<br>\n\n- Visualisation de relations complexes multi-variables\n\n- Traitement unifié de variables hétérogènes  \n\n- Réduction de dimension préservant les associations\n\n- Interprétation intuitive des proximités\n\n- Flexibilité dans l'encodage des variables\n\n\n## Limites et précautions\n\n<br>\n\nPerte d'information :\n\n- Variables continues → classes\n\n- Choix d'encodage critique\n\nInterprétation :\n\n- Proximités entre modalités de variables différentes\n\n- Attention aux artefacts d'encodage\n\n## Conclusion\n\n<br>\n\nL'ACM étend l'AFC au cas multi-variables grâce au codage disjonctif complet :\n\n- Transformation binaire préalable\n\n- Équivalence $Z$ ↔ Tableau de Burt $B$\n\n- Choix d'encodage\n\n- Visualisation des patterns complexes\n\nProchaine étape → éthique de l'analyse de données",
    "supporting": [
      "04-dimension-mca-slides-annotated_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}