--- 
title: "TP: Révision"
format:
  html: default
  pdf: 
    number-sections: true
    header-includes:
      - \usepackage{mathtools} 
---

Vous pouvez faire les exercices dans le langage de votre choix.


## Exercice 1: Estimer $\pi$

Dans cet exercice, on se propose d'estimer $\pi$ grâce à la méthode de Monte-Carlo. Le méthode de Monte-Carlo est une méthode algorithmique permettant d'estimer des quantités en utilisant des tirages aléatoires. Pour estimer $\pi$, l'idée est de générer des points dans un carré de façon uniforme et ensuite de compter la proportion de ces points qui sont dans le cercle unité.

1. Générer un nombre $n$ de points $(x, y)$ dans un carré de longueur $2$ centré à l'origine, i.e. $x \in [-1, 1]$ et $y \in [-1, 1]$.

2. Pour chaque point $n$, déterminer si le point appartient au cercle unité.

3. Calculer la proportion du nombre de points dans le cercle unité.

4. À partir du résultat précédent, estimer $\pi$.

5. Notons $\widehat{\pi}(n)$, l'estimateur de $\pi$ utilisant $n$ points générés. Tracer l'erreur d'estimation $\left| \pi - \widehat{\pi}(n) \right|$ en fonction de $n$.


## Exercice 2: Estimation d'intégrale

Dans cette exercice, on se propose d'estimer 
$$I = \int_{-1}^{1} \sqrt{1 - x^2} dx .$$

1. Calculer $I$ en utilisant une primitive.

2. Il est possible d'estimer $I = \int_{-1}^{1} f(x) dx$ à l'aide des sommes de Riemann $\widehat{I}(n) = \frac{1}{n}\sum_{i = 1}^{n} f(\frac{i}{n}), i = 1, \dots, n$. Estimer $I$ en utilisant les sommes de Riemann.

3. L'intégrale $I$ peut être vu comme l'espérance d'un variable aléatoire. $I = \mathbb{E}[f(U)]$, où $U \sim \mathcal{U}(-1, 1)$. On peut estimer $I$ en utilisant $\widetilde{I}(n) = \frac{1}{n} \sum_{i = 1}^{n} f(u_i)$, où les $u_i$ sont des réalisations de la variable aléatoire $U$. Estimer $I$ en utilisant cette méthode.

4. Comparer la qualité de ces deux estimateurs de $I$ en fonction de $n$.


## Exercice 3: La loi des gaz parfaits

Dans cet exercice, on se propose de vérifier la loi des gaz parfaits à partir des données. On rappelle que la loi des gaz parfaits est donnée par $PV = nRT$ où :

* $P$ est la pression à l'intérieur du volume considéré en Pascal (Pa);

* $V$ est le volume du gaz en m$^3$;

* $n$ est la quantité de matière en mole (mol);

* $R = 8.314$ est la constante universelle des gaz parfaits en J.mol$^{-1}$.K$^{-1}$;

* $T$ est la température à l'intérieur du volume considéré en Kelvin (K).

On conduit une expérience consistant à chauffer une quantité **fixe** de gaz dans un récipient fermé de volume **fixé**. La température $T$ en Kelvin et la pression $P$ en kPa sont enregistrées. On trouve les résultats suivants :


```{r}
#| echo: true 
#| eval: false 
temperature = [
  406, 296, 272, 449, 483, 439, 460, 276, 321, 462, 408, 322, 285,
  411, 491, 359, 453, 486, 413, 350, 263, 456, 390, 462, 389, 494,
  303, 496, 336, 460
]

pression = [
  1365, 982, 898, 1486, 1596, 1481, 1506, 906, 1085, 1542, 1367,
  1072, 955, 1379, 1633, 1186, 1499, 1606, 1378, 1156, 867, 1514,
  1306, 1525, 1287, 1665, 1020, 1635, 1118, 1529
]
```

1. Tracer la pression en fonction de la température. Est-ce que le graphique est linéaire ?

2. Construire la matrice $X = (1 | \text{temperature})$. La première colonne de $X$ est une colonne de $1$ et la deuxième colonne de $X$ est le vecteur des températures.

3. Calculer le vecteur $\beta = (X^{\top} X)^{-1} X^{\top} Y$ où $Y$ est le vecteur des pressions. 

4. Quelle est l'interprétation physique des éléments du vecteur $\beta$ ?

5. À quelle valeur de $\beta_0$, le premier coefficient de $\beta$, devrait-on s'attendre dans le cadre d'un gaz parfait ? Est-ce le cas ici ? Pourquoi ?

6. Supposons que le volume de gaz est de $10$dm$^3$. Estimer la quantité de matière $n$ en mole utilisé pour avoir les données.

