--- 
title: "TD: Révision"
format:
  html: default
  pdf: 
    number-sections: true
    header-includes:
      - \usepackage{mathtools} 
---

## Exercice 1: Un problème de vélo

Dans ce problème, on cherche à modéliser la répartition des vélos en libre service dans les différentes stations de l'université Laval. Le campus comporte cinq stations pouvant acceuillir un total de $136$ vélos ([lien](https://www.sc.ulaval.ca/mobilite-durable/se-deplacer-a-velo#:~:text=àVélo,l'avenue%20de%20la%20Médecine)): Abitibi-Prince (ABP), Alphone-Desjardins (ADJ), Charles-De Koninck (DKN), Ferdinand-Vandry (VND) et PEPS.

Supposons que tous les vélos sont retournés à une des cinq stations à la fin de la journée, i.e. pour chaque jour, il y a un moment dans la journée (par exemple, à minuit), où tous les vélos sont à une certaine station. Nous pouvons donc nous intéresser à ces stations à ce moment de la journée pour chaque jour. Nous cherchons à modéliser les movements des vélos de minuit pour un jour donné jusqu'à minuit du jour suivant. Nous trouvons que :

* pour les vélos empruntés à ABP, $50\%$ y retourne, $10\%$ vont à ADJ, $20\%$ vont à DKN et $20\%$ vont à VND.

* pour les vélos empruntés à ADJ, $30\%$ y retourne, $10\%$ vont à ABP, $10\%$ vont à DKN, $10\%$ vont à VND et $40\%$ vont au PEPS.

* pour les vélos empruntés à DKN, $80\%$ y retourne, $5\%$ vont à ADJ, et $15\%$ vont au PEPS.

* pour les vélos empruntés à VND, $50\%$ y retourne, $20\%$ vont à ABP, $5\%$ vont à ADJ, $15\%$ vont à DKN et $10\%$ vont au PEPS.

* pour les vélos empruntés au PEPS, $0\%$ y retourne, $25\%$ vont à ABP, $25\%$ vont à ADJ, $25\%$ vont à DKN et $25\%$ vont à VND.

1. Faire un graphe de la situation. 

2. Écrire la matrice $T$ tel que chaque entrée $t_{ij}$ corresponde à la probabilité de passer de la station $i$ à la station $j$, $i, j \in \{ \text{ABP}, \text{ADJ}, \text{DKN}, \text{VND}, \text{PEPS} \}$. On appelle cette matrice, la matrice de transition.

3. Quelle est la probabilité qu'un vélo soit à la station PEPS au jour 2 sachant qu'il était à la station ADJ au début ?

4. Supposons qu'il y ait $20$ vélos à ABP, $35$ vélos à ADJ, $26$ vélos à DKN, $45$ à VND et $10$ au PEPS. En utilisant une diagonalisation de la matrice $T$, donner la répartition des vélos après $10$ jours. 


## Exercice 2: Paradoxe des deux enfants

On cherche à modéliser les probabilités d'avoir des enfants d'un certain sexe. Dans toutes les questions, les enfants sont soit de sexe masculin, soit de sexe féminin, de façon équiprobable.

1. M. Gagnon a deux enfants. L'enfant aîné est une fille. Quelle est la probabilité que son deuxième enfant soit aussi une fille ?

2. Mme Tremblay a deux enfants. On lui pose la question suivante : "Avez-vous au moins un garçon ?" et elle répond : "Oui". Quelle est la probabilité que les deux enfants soient des garçons ? 

3. Est-ce que la probabilité de Mme Tremblay d'avoir deux garçons change si on lui pose la question suivante : "Indiquez moi le sexe de l'un de vos enfants." et qu'elle répond : "J'ai (au moins) un garçon." ?

4. On croise M. Gagnon dans la rue en train de se balader avec sa fille. On lui demande quel jour de la semaine elle est née. Elle nous répond: "Vendredi". Quelle est la probabilité que son deuxième enfant soit aussi une fille ?

## Exercice 3: La loi d'Ohm 

On cherche à calculer la valeur d'un résistance. Pour cela, on lui envoie un courant électrique (intensité en ampères, A) et on mesure la différence de potentiel entre les bornes de la résistance (tension en volt, V). On trouve les valeurs suivantes :

| Intensité (A) | Voltage (V) |
| ------------: | ----------: |
| 0.2           | 4.0         |
| 0.5           | 10.4        |
| 0.9           | 18.7        |
| 1.0           | 21.1        |
| 1.2           | 25.1        |
| 1.3           | 27.4        |
| 1.8           | 37.8        |

1. Calculer l'intensité moyenne et le voltage moyen.

2. Calculer les variances de l'intensité et du voltage.

3. Calculer la covariance entre l'intensité et le voltage.

4. La loi d'Ohm nous dit que l'intensité et le voltage sont proportionnelle suivant la relation $V = R A$ où $R$ est la valeur de la résistance en Ohm. Cette relation est équivalente à estimer un modèle linéaire entre l'intensité et le voltage. La résistance $R$ est donc donnée par le ratio entre la covariance entre l'intensité et le voltage et la variance de l'intensité (cf. cours de régression pour une preuve). Calculer la valeur de $R$. 

5. En reprenant les valeurs du tableau, vérifier la valeur de $R$. Pourquoi est-ce que l'on ne retrouve pas exactement les valeurs données ?
