--- 
title: Évaluations
format: 
  html: default
  pdf: default
--- 

## Modalités d'évaluations

Voici les différents examens prévus pour ce module.

| Titre      | Date    | Mode de travail | Pondération |
| ---------- | ------- | --------------- | ----------- |
| Examen 1   | 24 oct. 2025        | Individuel      | 30\%        |
| Examen 2   | 12 déc. 2025        | Individuel      | 50\%        |
| Projet d'analyse de données    | 02 déc. 2025        | En équipe       | 20\%        |

<p style="font-size:10px; ">Identification. Lors d'un examen, une carte d'identité avec photo admissible doit être déposée sur le coin de votre table. Les cartes admissibles sont la carte de l'Université Laval en plastique, un permis de conduire canadien, une carte d'assurance-maladie avec photo émise par une province canadienne ou un passeport canadien ou étranger.</p>

## Informations détaillées sur les évaluations

**Examen 1** 

Date et lieu: 24 octobre 2025 de 08h30 à 09h30

Mode de travail: Individuel

Pondération: 30\%

Remise de l'évaluation: Remise en main propre à l'enseignant

Directives de l'évaluation: Tout le contenu du cours (diapos, présentations en classe, lectures, ...) est susceptible d'être à l'examen.

Matériel autorisé: Tout matériel non-connecté à internet est autorisé. Calculatrice autorisée. L'utilisation d'outils d'IA n'est PAS autorisée pour cette examen.

Information supplementaire: [lien](./mcq.qmd).


**Examen 2**

Date et lieu: 12 décembre 2025 de 08h30 à 10h20

Mode de travail: Individuel

Pondération: 50\%

Remise de l'évaluation: Remise en main propre à l'enseignant

Directives de l'évaluation: Tout le contenu du cours (diapos, présentations en classe, lectures, ...) est susceptible d'être à l'examen.

Matériel autorisé: Tout matériel non-connecté à internet est autorisé. Calculatrice autorisée. L'utilisation d'outils d'IA n'est PAS autorisée pour cette examen.


**Projet d'analyse de données** 

Date et lieu: dû le 02 décembre 2025 à 17h00 

Mode de travail: En équipe 

Pondération: 20\%

Remise de l'évaluation: Via monPortail

Directives de l'évaluation: Tout retard sur la remise du projet entrainera la note de 0 pour cette partie. Il y aura une présentation des posters le 9 décembre entre 10h30 et 12h30. Les modalités exactes des présentations restent à définir. Dans le cas où l'affichage des posters ne puissent pas se faire au pavillon VCH, les présentations se feront dans la salle de classe PLT-3928. Le projet d'analyse de données consiste en la création d'un poster présentant une analyse de données. Le choix du sujet et de la problématique est laissé à votre discrétion. Il est recommandé d'utiliser les méthodes présentées en cours, mais ce n'est pas obligatoire. Dans tous les cas, attendez vous à avoir des questions sur les méthodes que vous présentez. Je suis bien entendu à votre disposition pour répondre à toutes questions (où trouver des données, comment faire un poster, ...). Merci de déposer un dossier .zip connant votre projet. Ce dossier doit contenir votre poster au format .pdf, votre code, ainsi que vos données. Si la taille du fichier de vos données est trop importante, merci de m'envoyer un email. Je m'occuperai de l'impression des posters. 

Matériel autorisé : L'utilisation d'outils d'IA est autorisée pour cette examen. Il convient cependant de proprement documenter son utilisation.


## Échelle des cotes 

| Cote | \% minimum | \% maximum |
| :--: | ---------: | ---------: |
| A+   | 92         | 100        |
| A    | 88         | 91.99      |
| A-   | 84         | 87.99      |
| B+   | 80         | 83.99      |
| B    | 75         | 79.99      |
| B-   | 70         | 74.99      |
| C+   | 65         | 69.99      |
| C    | 60         | 64.99      |
| C-   | 55         | 59.99      |
| D+   | 52         | 54.99      |
| D    | 50         | 51.99      |
| E    | 0          | 49.99      |

## Détails sur les modalités d'évaluation 

Conformément à la politique du Département de mathématiques et de statistique en matière d'amélioration et de consolidation de la connaissance du français, la qualité de l'écrit sera sanctionnée dans tous les travaux et examens. Un maximum de 10\% des points pourra être enlevé pour la qualité de la langue et de la rédaction.

Aucun retard n'est accepté pour la remise des travaux. Un retard entraîne automatiquement une note de zéro.

Toute reprise d'évaluation accordée par la politique de reprise d'évaluation du Département aura lieu lors des dates de reprises officielles de la faculté. Pour toute demande de révision de note, vous devez suivre la procédure du chapitre 4 du Réglement des études. Vous trouverez un formulaire à remplir à l'adresse suivante: [lien](https://www.fsg.ulaval.ca/departements/departement-de-mathematiques-et-de-statistique/etudier/reglements-et-documents-officiels-en-mathematiques-et-statistique).

Les séances d'examen de reprise FSG pour la session d'automne 2025 auront lieu :

* Le jeudi 30 octobre 2025, local à déterminer, de 9h à 12h et/ou de 13h30 à 16h30.

* Le jeudi 18 décembre 2025, local à déterminer, de 9h à 12h et/ou de 13h30 à 16h30.


## Absence à une activité obligatoire

Ces modalités s'appliquent en vertu des articles 4.41 et 4.42 du Réglement des études de l'Université Laval: 

* **Article 4.41:** Tout défaut de se soumettre à une activité d'évaluation entraîne la note de zéro pour cette activité d'évaluation, à moins que l'étudiante ou l'étudiant ne démontre que cette omission est attribuable à des motifs sérieux.

* **Article 4.42:** La reprise d'une évaluation est possible pour des motifs sérieux. Elle se fait selon les modalités prévues par l'unité responsable de l'activité de formation.

La reprise d'une évaluation peut donc execptionnellement être autorisée pour des motifs jugés sérieux, dans la mesure où la procédure décrite ci-dessous est respectée. 

**Motifs d'absence jugés sérieux**

Les motifs suivants sont jugés sérieux et donc acceptables pour demander une reprise d'évaluation: 

  - maladie ou accident empêchant de se déplacer;
  - hospitalisation;
  - maladie grave ou décès d'un proche;
  - participation à une activité sportive de haut niveau;
  - convocation en cour de justice.

**Procédure à suivre**

Dès que possible et au plus tard cinq (5) jours ouvrables après la date de l'évaluation (ou dans certains cas, avant la date de l'évaluation, dès que le motif sera connu), l'étudiante ou l'étudiant qui veut faire une demande de reprise d'évaluation doit remplir et soumettre le formulaire électronique "[Demande de reprise d'une évaluation](https://ulavaldti.sharepoint.com/sites/FSG-reprise-dexamens-et-reconnaissance-de-cours/Lists/Demande%20de%20reprise%20dexamens/NewForm.aspx?Source=https%3A%2F%2Fulavaldti.sharepoint.com%2Fsites%2Ffsg-demande-de-reprise-examen%2FLists%2FDemande%2520de%2520reprise%2520dexamens%2FEtudiant.aspx%3FCT%3D1724436857013%26OR%3DOWA%252DNT%252DMail%26CID%3D42d5014c%252D8fb5%252D8232%252Dbd8f%252D69c67e3a9cdd&ContentTypeId=0x010020B04CCB63D0044D860D6BB7B9C92629007488899A2536D44DA71B9101B9C72D92&RootFolder=)" en prenant soin d'y joindre les pièces justificatives requises.

Pour avoir plus de détail sur les procédures à suivre et les motifs sérieux pouvant donner droit à une reprise d'évaluation, consulter le document "[Modalités et procédure de reprise d'une évaluation sommative à la Faculté des sciences et de génie](https://www.fsg.ulaval.ca/fileadmin/site_facultaire/Espace_facultaire/Étudiants/Politiques_facultaires/Modalités_reprise_évaluation_FSG_A24.pdf)" disponible sur le site web de la FSG.

Dans certains cas, la ou le responsable du cours pourrait adopter une procédure simplifiée de gestion des demandes de reprises d'évaluation, tout en respectant les critères décrits dans cette politique. Dans ces cas, des explications particulières seront données à cet effet dans le plan de cours et présentées lors de la première séance.

## Politique sur la sécurité dans les laboratoires informatiques 

Pour utiliser les laboratoires informatiques, il faut avoir pris connaissance de la Politique de sécurité et vous engagez à vous y conformer : [lien](www.fsg.ulaval.ca/securite-labo-info).

Pour toute assistance technique, veuillez écrire à [<aide@fsg.ulaval.ca>]. En cas d’urgence, composez le 418-656-5555, poste 555 ou utilisez un téléphone rouge situé à proximité.

## Politique sur l'utilisation d'appareils électroniques

La politique sur l'utilisation d'appareils électroniques de la Faculté des Sciences et de Génie peut être consultée à l'adresse: [lien](https://www.fsg.ulaval.ca/fileadmin/site_facultaire/Espace_facultaire/Étudiants/Politiques_facultaires/_Calculatrices-autorisées-FSG_20250221.pdf).

## Politique sur le plagiat et la fraude académique 

**Règles disciplinaires**

Tout étudiant qui commet une infraction au Règlement disciplinaire à l'intention des étudiants de l'Université Laval dans le cadre du présent cours, notamment en matière de plagiat, est passible des sanctions qui sont prévues dans ce règlement. Il est très important pour tout étudiant de prendre connaissance des articles 23 à 46 du Règlement disciplinaire. Celui-ci peut être consulté à l'adresse suivante: [lien](https://www.ulaval.ca/sites/default/files/notre-universite/direction-gouv/Documents_officiels/Reglements/Reglement_disciplinaire_intention_etudiants.pdf).

**Plagiat**

Tout étudiant est tenu de respecter les règles relatives au plagiat. Constitue notamment du plagiat le fait de: 

  i. copier textuellement un ou plusieurs passages provenant d'un ouvrage sous format papier ou électronique sans mettre ces passages entre guillemets et sans en mentionner la source;

  ii. résumer l'idée originale d'un auteur en l'exprimant dans ses propres mots (paraphraser) sans en mentionner la source;

  iii. traduire partiellement ou totalement un texte sans en mentionner la provenance;

  iv. remettre un travail copié d'un autre étudiant (avec ou sans l'accord de cet autre étudiant);

  v. remettre un travail téléchargé d'un site d'achat ou d'échange de travaux scolaires.

L'Université Laval étant abonnée à un service de détection de plagiat, il est possible que l'enseignant soumette vos travaux pour analyse.

## Étudiants ayant une situation de handicap liée à une limitation fonctionnelle 

Afin de bénéficier de mesures d'accommodement pour les cours ou les examens, un rendez-vous avec une conseillère ou un conseiller du Centre d'aide aux étudiants travaillant en Accueil et soutien aux étudiants en situation de handicap (ACSESH) est nécessaire. Pour ce faire, les étudiants présentant une situation de handicap liée à une limitation fonctionnelle permanente doivent visiter le site "[Accommodement](https://monportail.ulaval.ca/accommodement)" et prendre un rendez-vous, le plus tôt possible.

Au cours de la semaine qui suit l'autorisation des mesures, leur activation doit être effectuée dans "[Accommodement](https://monportail.ulaval.ca/accommodement)" pour assurer leur mise en place.

Les étudiants ayant déjà obtenu des mesures d'accommodements scolaires doivent procéder à l'activation de leurs mesures pour les cours et/ou les examens dans "[Accommodement](https://monportail.ulaval.ca/accommodement)" afin que celles-ci puissent être mises en place. Il est à noter que l'activation doit s'effectuer au cours de deux premières semaines de cours.

Les étudiants concernés recevront par la suite des facultés et départements responsables de leurs cours les informations détaillées sur les modalités permettant d'appliquer les mesures d'accommodement identifiées.
