---
title: Grading
format: 
  html: default
  pdf: default
--- 

## Assessment procedures

Here are the examinations for this module.

| Title      | Date       | Mode of work    | Weighting   |
| ---------- | -------    | --------------- | ----------- |
| Exam 1     |            |  Individual     | 25\%        |
| Exam 2     |            |  Individual     | 50\%        |
| Project    |            |  Team           | 25\%        |

<p style=“font-size:10px;”>Identification. During an exam, an eligible photo ID card must be placed on the corner of your table. Eligible cards are a plastic Université Laval card, a Canadian driver's license, a photo health insurance card issued by a Canadian province, or a Canadian or foreign passport.</p>

## Detailed assessment information

**Exam 1** 

Date and location: 

Mode of work: Individual

Weighting: 25\%

Submission of assessment: 

Assessment guidelines: All course content may be examined. 

Materials allowed: no restrictions. 

Additional information: [link](./mcq.qmd).


**Exam 2**

Date and place: 

Mode of work: Individual

Weighting: 50\%

Submission of assessment: 

Assessment guidelines: All course content is subject to examination. 

Materials allowed: no restrictions. 


**Project** 

Date and place: 

Mode of work: Team work 

Weighting: 25\%

Submission of assessment: 

Assessment guidelines: 

Materials allowed: no restrictions. 


## Rating scale 

| Rating \% minimum | \% maximum |
| :--: | ---------: | ---------: |
| A+   | 92         | 100        |
| A    | 88         | 91.99      |
| A-   | 84         | 87.99      |
| B+   | 80         | 83.99      |
| B    | 75         | 79.99      |
| B-   | 70         | 74.99      |
| C+   | 65         | 69.99      |
| C    | 60         | 64.99      |
| C-   | 55         | 59.99      |
| D+   | 52         | 54.99      |
| D    | 50         | 51.99      |
| E    | 0          | 49.99      |

## Assessment details 

In accordance with the Department of Mathematics and Statistics' policy of improving and consolidating the knowledge of French, the quality of writing will be assessed in all assignments and examinations. A maximum of 10% of points may be deducted for the quality of language and writing.

No late submissions will be accepted.

Any resits granted under the Department's resit policy will take place on the faculty's official resit dates. To request a grade revision, you must follow the procedure set out in Chapter 4 of the Academic Regulations. You will find a form to complete at the following address: [link](https://www.fsg.ulaval.ca/departements/departement-de-mathematiques-et-de-statistique/etudier/reglements-et-documents-officiels-en-mathematiques-et-statistique).



## Absence from a mandatory activity

These conditions apply in accordance with articles 4.41 and 4.42 of the Réglement des études de l'Université Laval: 

* **Article 4.41:** Any failure to submit to an evaluation activity will result in a grade of zero for that evaluation activity, unless the student demonstrates that the omission is attributable to serious reasons.

* **Article 4.42:** An evaluation may be repeated for serious reasons. This is done in accordance with the procedures laid down by the unit responsible for the training activity.

The retaking of an assessment may therefore exceptionally be authorized for reasons deemed serious, as long as the procedure described below is followed. 

**Reasons for absence deemed to be serious**

The following reasons are considered serious and therefore acceptable for requesting a retake of an assessment: 

  - illness or accident preventing travel;
  - hospitalization;
  - serious illness or death of a close relative;
  - participation in a high-level sporting activity;
  - court summons.

**Procedure to follow**

As soon as possible and no later than five (5) working days after the evaluation date (or in certain cases, before the evaluation date, as soon as the reason is known), the student who wishes to apply for an evaluation re-sit must complete and submit the electronic form "[Application to re-sit an evaluation](https://ulavaldti.sharepoint.com/sites/FSG-reprise-dexamens-et-reconnaissance-de-cours/Lists/Demande%20de%20reprise%20dexamens/NewForm.aspx?Source=https%3A%2F%2Fulavaldti.sharepoint.com%2Fsites%2Ffsg-demande-de-reprise-examen%2FLists%2FDemande%2520de%2520reprise%2520dexamens%2FEtudiant.aspx%3FCT%3D1724436857013%26OR%3DOWA%252DNT%252DMail%26CID%3D42d5014c%252D8fb5%252D8232%252Dbd8f%252D69c67e3a9cdd&ContentTypeId=0x010020B04CCB63D0044D860D6BB7B9C92629007488899A2536D44DA71B9101B9C72D92&RootFolder=)", taking care to attach the required supporting documents.

For more details on the procedures to be followed and the serious grounds for retaking an evaluation, please consult the document "[Modalités et procédure de reprise d'une évaluation sommative à la Faculté des sciences et de génie](https://www.fsg.ulaval.ca/fileadmin/site_facultaire/Espace_facultaire/Étudiants/Politiques_facultaires/Modalités_reprise_évaluation_FSG_A24.pdf)" available on the FSG website.

In certain cases, the course leader may adopt a simplified procedure for managing requests to repeat an evaluation, while respecting the criteria described in this policy. In such cases, specific explanations will be provided in the course syllabus and presented at the first session.

## Policy on the use of electronic devices

The Faculty of Science and Engineering's policy on the use of electronic devices can be consulted at: [link](https://www.fsg.ulaval.ca/fileadmin/site_facultaire/Espace_facultaire/Étudiants/Politiques_facultaires/_Calculatrices-autorisées-FSG_20250221.pdf).

## Plagiarism and academic fraud policy 

**Disciplinary rules**

Any student who commits an infraction of the Disciplinary Regulations for Laval University students in the context of this course, particularly in the area of plagiarism, is subject to the sanctions provided for in these regulations. It is very important for all students to read articles 23 to 46 of the Disciplinary Regulations. These can be consulted at the following address: [link](https://www.ulaval.ca/sites/default/files/notre-universite/direction-gouv/Documents_officiels/Reglements/Reglement_disciplinaire_intention_etudiants.pdf).

**Plagiarism**

All students are required to comply with the rules governing plagiarism. In particular, plagiarism is defined as: 

  i. copying verbatim one or more passages from a work in paper or electronic format without placing these passages in quotation marks and without mentioning the source;

  ii. summarizing an author's original idea by expressing it in one's own words (paraphrasing) without mentioning the source;

  iii. translate a text in whole or in part without mentioning its source;

  iv. submit work copied from another student (with or without that other student's consent);

  v. submit work downloaded from a site for the purchase or exchange of school work.

As Université Laval subscribes to a plagiarism detection service, your teacher may submit your work for analysis.


## Students with disabilities related to functional limitations 

In order to benefit from accommodation measures for courses or exams, an appointment with a counsellor from the Centre d'aide aux étudiants travaillant en Accueil et soutien aux étudiants en situation de handicap (ACSESH) is necessary. Students with a disability related to a permanent functional limitation should visit "[Accommodement](https://monportail.ulaval.ca/accommodement)" and book an appointment as soon as possible.

During the week following authorization of the measures, they must be activated in "[Accommodement](https://monportail.ulaval.ca/accommodement)" to ensure that they are in place.

Students who have already obtained academic accommodation measures must activate their measures for courses and/or exams in "[Accommodement](https://monportail.ulaval.ca/accommodement)" so that they can be implemented. Please note that activation must take place within the first two weeks of classes.

Students concerned will then receive detailed information from the faculties and departments responsible for their courses on how to apply the accommodation measures identified.

